### PR TITLE
feat: i18n placeholders

### LINKED ISSUE #51: Support for i18n via placeholders
There are several places where we need support for localizing strings in the ui like e.g. in the search results and the placeholder used for the search input field:

Bildschirm­foto 2023-04-05 um 11 21 07

We should use [placeholder](https://www.hlx.live/docs/placeholders) support to have individual sheets per language with the values to use. 

As we might want to have other sheets for unrelated lookups as well the name of the sheet will be **i18n** instead of **placeholders**

### PR DESCRIPTION
**Pull request by karlpauls**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #51 

Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/
- After: https://51-i18n--mammotome--hlxsites.hlx.page/en/

### CODE REVIEW

**Comment by karlpauls** [comment]
I changed the fetchPlaceholders method somewhat to in the first place lookup i18n instead of placeholders but furthermore, to make it more robust for failures. I created an upstream issue with the boilerplate as well to see if this should be a more general fix (https://github.com/adobe/helix-project-boilerplate/issues/203)

**Comment by karlpauls** [comment]
On second thought, in https://github.com/hlxsites/mammotome/pull/47 we decided that it is safer to not blindly trust author provided input as html - hence, I added another commit to make sure we use textContent if values from the placeholders are used.

**Comment by solaris007** [comment]
it is likely, that placeholders will be used on every page. if this is the case, you could load the placeholders delayed and query from the `window.placeholders` object instead. The ability to specify a default text would also be nice.

https://github.com/hlxsites/elco-aerotop-sg/pull/40/files#diff-2c92a267a7d73a4c0a3dd9d6d960e4fbbf07254a75154691fc24fc9beb4f9d43
https://github.com/hlxsites/elco-aerotop-sg/pull/40/files#diff-a5ee87ff9063f921ba01933977e6164e5729551986030f0ed7eb747bcffb740f

**Comment by karlpauls** [comment]
@solaris007, my placeholder function already has a default text option. However, I agree it could be named better to make that more clear and additionally, I guess, yes - it might be better to move it to lib-franklin.js as in [0].

I'm not sure about moving it to delayed - that would mean we'd have to make sure we do all the references after delayed which e.g. in the search input is already not the case. I suppose it would be doable to basically have a delayed decorateSearch - do you want me to work on that?

[0] https://github.com/hlxsites/elco-aerotop-sg/pull/40/files#diff-a5ee87ff9063f921ba01933977e6164e5729551986030f0ed7eb747bcffb740f

**Comment by karlpauls** [comment]
@solaris007, I moved and renamed the function.

**Review by solaris007 — APPROVED** [review]
LGTM

**Comment by karlpauls** [comment]
@solaris007, I'm now only invoking the getPlaceholders when needed (i.e., after the user clicked on the search button - or if this is a search link) and as such, the request is delayed. To speed things up, I added a fetchPlaceholders to the delayed.js so that the placeholders are loaded already in the normal cases. I think this should address your points - please PTAL again.

**Pull request merged**
