### PR TITLE
feat: video player

### LINKED ISSUE #25: Video Player
Add video player. This could be done with auto-blocking, i.e. by embedding the video player when encountering a-tags with a youtube source.

Should have features:
- youtube source
- can be used independently or  in columns / other blocks
- can be on the same page multiple times
- thumbnail image
- overlayed play button
- after clicking, video features as per original site

Mobile (here multiple on same page):
Screenshot 2023-03-17 at 11 35 26

Desktop (here multiple on same page):
Screenshot 2023-03-17 at 11 36 02

Screenshot 2023-03-17 at 11 40 07

Inspirations:
- https://github.com/hlxsites/elco-aerotop-sg/tree/main/blocks/youtube-player
- https://github.com/adobe/helix-block-collection/tree/main/blocks/video

### PR DESCRIPTION
**Pull request by solaris007**
Add video (youtube) player with two-column support. The youtube URL supports `/wach` or `/embed` (share) links.

Fix #25 

Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/dj-test
- After: https://25-video-player--mammotome--hlxsites.hlx.page/en/dj-test

Content (two colums):
Screenshot 2023-03-27 at 09 25 41

### CODE REVIEW

**Review by Acidham — COMMENTED** [review]
Play button resizing:
Screenshot 2023-03-28 at 08 22 30

Viedo thumbnail size:
Screenshot 2023-03-28 at 08 09 30

**Comment by solaris007** [comment]
@Acidham play button fixed in https://github.com/hlxsites/mammotome/pull/39/commits/1f4bd3516ed6b311e7afc3f6a45395dcbab84f28

**Comment by solaris007** [comment]
@Acidham video thumbnail size difference is a side effect of me having uploaded thumbnails of different aspect ratio in the content. an author would fix that by using same-sized images everywhere.

**Comment by Acidham** [comment]
@solaris007 Video title is center aligned. I also found pages where title is aligned at the bottom, centered.  

Screenshot 2023-03-28 at 09 58 00

Screenshot 2023-03-28 at 09 54 40

**Comment by solaris007** [comment]
@Acidham - centering fixed in https://github.com/hlxsites/mammotome/pull/39/commits/fb097d23d962dbd5337c4fa57777bdbc565ea5a4

I decided to only support titles on top of the video to standardize.

**Review by Acidham — APPROVED** [review]

**Comment by chicharr** [comment]
LGTM

**Pull request merged**
