### PR TITLE
fix: cards padding

### LINKED ISSUE #262: Style: Cards in mobile view
Wrong text alignment and size of Cards (three-columns) in the mobile version:

Screenshot 2023-06-15 at 11 32 02

mammotome.com
Screenshot 2023-06-15 at 11 32 33

### PR DESCRIPTION
**Pull request by dzehnder**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #262

Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/
- After: https://262-fix-cards-mobile--mammotome--hlxsites.hlx.page/us/en/

### CODE REVIEW

**Review by Acidham — CHANGES_REQUESTED** [review]
Cards are bigger in height on the original page (left) also text size is bigger
Screenshot 2023-06-15 at 14 41 43

**Comment by smiroslav** [comment]
Screenshot 2023-06-15 at 15 52 41

Title of the card should not be a link at the same time.

Screenshot 2023-06-15 at 15 56 04

**Comment by smiroslav** [comment]
@dzehnder I have changed cards block in sharepoint and did preview

**Comment by solaris007** [comment]
@dzehnder @smiroslav @Acidham anything else required here?

**Comment by Acidham** [comment]
@solaris007 the cards are still too big
Screenshot 2023-06-27 at 08 05 24


@smiroslav can you please ensure that the Cars are fully documented: https://github.com/hlxsites/mammotome/blob/doc/docs/blocks/cards.md

**Comment by dzehnder** [comment]
@Acidham please have a look again, they should look the same now as on the original page

**Review by solaris007 — APPROVED** [review]

**Review by smiroslav — DISMISSED** [review]

**Review by Acidham — CHANGES_REQUESTED** [review]
Breaks the other Cards with text. The box is too small.
Screenshot 2023-06-27 at 14 57 22

**Review by Acidham — APPROVED** [review]

**Pull request merged**
